refresh_rate: 30 seconds

appenders:
  console:
    kind: console
    encoder:
      kind: json
  file:
    kind: file
    path: "logs/rpc.log"
    encoder:
      kind: json
    append: true

root:
  level: info
  appenders:
    - console
    - file

loggers:
  volo_boot_rpc:
    level: debug
    appenders:
      - console
      - file
    additive: false